import {describe,expect,it}from'vitest';import{createTimer,pauseTimer,resumeTimer,startTimer,tickTimer}from'./focusTimer';import{experienceForLevel,focusExperience,levelFromExperience,applyDailyCheckIn}from'./progression';import{canTransition,transition}from'./stateMachine';import{behaviorsForTraits,chooseBehavior}from'./personality';import{filterDialogue}from'./dialogue';import{createDefaultSave,defaultSettings}from'./defaults';import{migrateSave}from'../services/persistence';
import{familiarStyles,styleDialogue}from'./styleProfile';
describe('focus timer',()=>{it('starts, pauses, resumes and completes',()=>{let t=startTimer(createTimer(1));t=tickTimer(t,20);expect(t.remainingSeconds).toBe(40);t=pauseTimer(t);expect(tickTimer(t,10).remainingSeconds).toBe(40);t=resumeTimer(t);expect(tickTimer(t,40).status).toBe('complete')})});
describe('progression',()=>{it('uses a slow increasing curve',()=>{expect(experienceForLevel(4)).toBeGreaterThan(experienceForLevel(3));expect(levelFromExperience(experienceForLevel(5))).toBe(5);expect(focusExperience(25)).toBe(20)});it('awards check-in once',()=>{expect(applyDailyCheckIn(false)).toBe(8);expect(applyDailyCheckIn(true)).toBe(0)})});
describe('state machine',()=>{it('prevents conflicting transitions',()=>{expect(canTransition('sleeping','celebrating')).toBe(false);expect(transition('sleeping','celebrating')).toBe('sleeping');expect(transition('focused','celebrating')).toBe('celebrating')})});
describe('personality',()=>{it('selects trait-specific behaviors',()=>{expect(behaviorsForTraits(['sleepy'])).toContain('nap');expect(chooseBehavior(['calm'],0)).toBe('look')})});
describe('persistence',()=>{it('has safe defaults and migrates old saves',()=>{expect(defaultSettings.disableFlashing).toBe(true);const migrated=migrateSave({schemaVersion:1,pet:{name:'Moss'},settings:{sounds:true}});expect(migrated.schemaVersion).toBe(2);expect(migrated.pet.name).toBe('Moss');expect(migrated.settings.disableFlashing).toBe(true)});it('creates a complete save',()=>expect(createDefaultSave().pet.type).toBe('small-dragon'))});
describe('dialogue',()=>it('filters by context',()=>expect(filterDialogue({category:'idle',traits:['curious'],mood:'calm'}).some(x=>x.id==='idle-dust')).toBe(true)));
describe('audience styles',()=>it('changes the whole experience profile',()=>{expect(Object.keys(familiarStyles)).toHaveLength(4);expect(familiarStyles.retro.rendering).toBe('pixel');expect(familiarStyles['dark-fantasy'].dialogueVoice).toBe('gothic');expect(styleDialogue('anime')).toContain('together')}));
