import {create} from 'zustand';
import type {PetState,SaveData} from '../domain/types';
import type {TimerState} from '../domain/focusTimer';
import {createTimer,startTimer,pauseTimer,resumeTimer,tickTimer} from '../domain/focusTimer';
import {focusExperience,levelFromExperience} from '../domain/progression';
import {loadSave,saveData} from '../services/persistence';
import {transition} from '../domain/stateMachine';
interface FamiliarStore{data:SaveData;petState:PetState;timer:TimerState;bubble:string|null;setData:(data:SaveData)=>void;patchSettings:(patch:Partial<SaveData['settings']>)=>void;rename:(name:string)=>void;react:()=>void;snack:()=>void;sleep:()=>void;startFocus:(minutes:number)=>void;pauseFocus:()=>void;resumeFocus:()=>void;endFocus:()=>void;tick:()=>void;dismissBubble:()=>void}
const persist=(data:SaveData)=>{saveData(data);return data};
export const useFamiliarStore=create<FamiliarStore>((set,get)=>({data:loadSave(),petState:'idle',timer:createTimer(25),bubble:'Ready when you are.',setData:data=>set({data:persist(data)}),patchSettings:patch=>set(s=>({data:persist({...s.data,settings:{...s.data.settings,...patch}})})),rename:name=>set(s=>({data:persist({...s.data,pet:{...s.data.pet,name}})})),react:()=>set(s=>({petState:transition(s.petState,'interacting'),bubble:'I found a very important dust particle.',data:persist({...s.data,pet:{...s.data.pet,bond:Math.min(100,s.data.pet.bond+1)}})})),snack:()=>set(s=>({petState:transition(s.petState,'eating'),bubble:'A worthy snack.',data:persist({...s.data,pet:{...s.data.pet,hunger:Math.min(100,s.data.pet.hunger+12)}})})),sleep:()=>set(s=>({petState:transition(s.petState,'sleeping'),bubble:null})),startFocus:minutes=>set({timer:startTimer(createTimer(minutes)),petState:'focused',bubble:'I’ll guard the desk.'}),pauseFocus:()=>set(s=>({timer:pauseTimer(s.timer)})),resumeFocus:()=>set(s=>({timer:resumeTimer(s.timer)})),endFocus:()=>set({timer:createTimer(get().data.settings.defaultFocusMinutes),petState:'idle'}),tick:()=>set(s=>{const timer=tickTimer(s.timer);if(timer.status!=='complete'||s.timer.status==='complete')return{timer};const minutes=Math.round(timer.durationSeconds/60),xp=s.data.pet.experience+focusExperience(minutes);return{timer,petState:'celebrating',bubble:'Good work.',data:persist({...s.data,pet:{...s.data.pet,experience:xp,level:levelFromExperience(xp),totalFocusSessions:s.data.pet.totalFocusSessions+1,totalFocusMinutes:s.data.pet.totalFocusMinutes+minutes},daily:{...s.data.daily,focusMinutes:s.data.daily.focusMinutes+minutes,completedSessions:s.data.daily.completedSessions+1}})}}),dismissBubble:()=>set({bubble:null})}));
